### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by hanslovsky** [scijava/scijava-repl-fx#1]
This needs a license. It seems that scijava projects generally use AGPL, should I use the same license here @ctrueden?

**Comment by ctrueden** [comment]
> It seems that scijava projects generally use AGPL

Heh, you peeked at scripting-kotlin, eh? That is literally the only component that uses AGPL. Most of them are BSD-2.

I do not remember why scripting-kotlin uses AGPL, but probably because a dependency is licensed that way?

**Comment by ctrueden** [comment]
Anyway, AGPL is viral, so I guess this component must be AGPL too, since scripting-kotlin is AGPL. See also:
* https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant
* https://softwareengineering.stackexchange.com/questions/263063/how-viral-is-the-affero-gpl

But if scripting-kotlin does not legally need to be APGL, then I would prefer it (and this component) not to be. It will create wrinkles later if we ever want to ship this stuff with Fiji.

**Comment by hanslovsky** [comment]
Guilty as charged. :smile: 

[scripting-kotlin](https://github.com/scijava/scripting-kotlin/blob/master/pom.xml) has only Kotlin dependencies that are all Apache 2.0 afaict (plus scijava-common). I agree that it is probably better to update the scripting-kotlin license if appropriate.

**Comment by ctrueden** [comment]
scijava/scripting-kotlin@7fb0f0cc7a9d0809942b7687507be30abeabb82d

**Comment by hanslovsky** [comment]
Thanks @ctrueden 

scijava/scripting-kotlin#3
